### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [jonasmaziero/LibForQ-v1#1]
I suggest adding topics such as `rng`, `random-number-generator` in the About section at https://github.com/jonasmaziero/LibForQ-v1

**Comment by jonasmaziero** [comment]
Done

**Comment by Beliavsky** [comment]
No, please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by jonasmaziero** [comment]
I'm sorry. I did not understand your request. Please, can you be more specific? 
By the way, a more detailed discussion about the subjects of this repository can be found in this article:
J. Maziero, “Fortran Code for Generating Random Probability Vectors, Unitaries, and Quantum States,” Frontiers in ICT, vol. 3, 2016, Accessed: Oct. 12, 2023. [Online]. Available: https://www.frontiersin.org/articles/10.3389/fict.2016.00004
Best regards, 
Jonas Maziero

**Comment by Beliavsky** [comment]
If you look at https://github.com/jannisteunissen/rng_fortran for example, you see tags such as [random](https://github.com/topics/random) [rng](https://github.com/topics/rng) [random-number-generator](https://github.com/topics/random-number-generator) [xoroshiro](https://github.com/topics/xoroshiro) [xoroshiro128](https://github.com/topics/xoroshiro128) in the About section. I am suggesting that you add similar tags in the About section of your repo. How to do so is described in the previous link.

**Comment by jonasmaziero** [comment]
Dear Jannis, thank you very much for the tip. Now I think it's done.
Best regards, 
Jonas
